language: java
jdk:
  -openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r aws-springboot2-jungcali *
  - mkdir -p deploy
  - mv aws-springboot2-jungcali.zip deploy/aws-springboot2-jungcali.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jungcali-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-dployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jungcali-springboot-build
    key: aws-springboot2-jungcali.zip
    bundle_type: zip
    application: aws-springboot2-jungcali-group
    region: ap-northeast-2
    wait-until-dployed: true

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jungcali94@gmail.com